FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=kkd1234
ENV WEBHOOK_URL=https://n8n-kkd.up.railway.app/
ENV N8N_PORT=5678
ENV GENERIC_TIMEZONE=Asia/Bangkok
